// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyBYql0Vh1uFGUKfViIqnzmJp5nphrPQKGQ',
    appId: '1:746502358122:web:3a282ad08445165cd2f613',
    messagingSenderId: '746502358122',
    projectId: 'electronicbusinesscard-f3372',
    authDomain: 'electronicbusinesscard-f3372.firebaseapp.com',
    storageBucket: 'electronicbusinesscard-f3372.firebasestorage.app',
    measurementId: 'G-KE9D803T4S',
  );

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyCeJLheB8Z2gjs-6CCSSc3FqLNghBGzqNY',
    appId: '1:746502358122:android:7a669b1e61505255d2f613',
    messagingSenderId: '746502358122',
    projectId: 'electronicbusinesscard-f3372',
    storageBucket: 'electronicbusinesscard-f3372.firebasestorage.app',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyBTxyaDrAKgqzyVw4Jkbc6y0qZbBi84808',
    appId: '1:746502358122:ios:ced50d608921d9e9d2f613',
    messagingSenderId: '746502358122',
    projectId: 'electronicbusinesscard-f3372',
    storageBucket: 'electronicbusinesscard-f3372.firebasestorage.app',
    iosBundleId: 'com.example.techcardMobile',
  );

  static const FirebaseOptions macos = const FirebaseOptions(
    
    apiKey: 'AIzaSyBTxyaDrAKgqzyVw4Jkbc6y0qZbBi84808',
    appId: '1:746502358122:ios:ced50d608921d9e9d2f613',
    messagingSenderId: '746502358122',
    projectId: 'electronicbusinesscard-f3372',
    storageBucket: 'electronicbusinesscard-f3372.firebasestorage.app',
    iosBundleId: 'com.example.techcardMobile',
  );

  static const FirebaseOptions windows = const FirebaseOptions(
    apiKey: 'AIzaSyBYql0Vh1uFGUKfViIqnzmJp5nphrPQKGQ',
    appId: '1:746502358122:web:5b15bd6e8d8d19d6d2f613',
    messagingSenderId: '746502358122',
    projectId: 'electronicbusinesscard-f3372',
    authDomain: 'electronicbusinesscard-f3372.firebaseapp.com',
    storageBucket: 'electronicbusinesscard-f3372.firebasestorage.app',
    measurementId: 'G-94HFPPC7SN',
  );
}
